{% set name = "skytag" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skytag-{{ version }}.tar.gz
  sha256: 1a0a4d9762f4e7c88f330d7cdd3f846ed0d2266adf13dff9bae90813d1a83ebd
  
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - skytag = skytag.cl_utils:main

requirements:
  host:
    - pip
    - python >=3.9
    - wheel
    - setuptools
  run:
    - python >=3.9
    - pyyaml
    - fundamentals
    - astropy
    - astropy-healpix
    - numpy
    - pandas

test:
  imports:
    - skytag

about:
  home: https://github.com/thespacedoctor/skytag
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Annotate transient sources or galaxies with the percentage credibility region they reside within on a given HealPix sky map.
  doc_url: https://skytag.readthedocs.io/en/main/
  dev_url: https://github.com/thespacedoctor/skytag

extra:
  recipe-maintainers:
    - thespacedoctor
